version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0-browsers
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidadSoftware2024

    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-repo-{{ checksum "pom.xml" }}

      - run:
          name: Install MySQL Client
          command: sudo apt-get update && sudo apt-get install -y mysql-client

      - run:
          name: Wait for MySQL
          command: sleep 30

      - run:
          name: Create database 
          command: mysql -h 127.0.0.1 -u root -p123456 calidad < src/resources/crearDB.sql

      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      - run:
          name: Unit Tests
          command: mvn -Dtest=UserServiceUnitTest -Dsurefire.printSummary=true test

      - run:
          name: Integration Tests
          command: mvn -Dtest=UserServiceTest -Dsurefire.printSummary=true test

      - run:
          name: Functional Tests
          command: mvn -Dtest=MernTest -Dsurefire.printSummary=true test

  deployment:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - run:
          name: Deploy
          command: echo "Deploy hecho"

workflows:
  build_and_test:
    jobs:
      - build-and-test
      - deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main